# Compiles and then creates the Bot image
---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Build vars needed for the build_application_tasks
    container_space: forte
    build_name: bot
    container_name: bot
    compiler_name: compiler

  tasks:
    - name: Include build tasks list
      include_tasks: build_application_tasks.yml